### ISSUE TITLE
Configurable Device Discovery

### ISSUE THREAD

**Issue by dezren39** [fiberpunk1/SentryAPI#1]
Hello, I haven't had a chance to use this yet, but I can see that the part where device discovery checks the last quartet won't entirely work for me. Is it possible to set that as the default, but also allow for configurable scan-range?

**Comment by fiber-punk** [comment]
![image](https://user-images.githubusercontent.com/85388178/185289736-cfc70fa2-3e54-44a2-9cab-b82e6a7c460f.png)
Different network segments can be set here, and this also applies to Sentry.
Is this the feature you need?

**Comment by dezren39** [comment]
This is great, I think so, yeah!
